/* ============================================================
 * learning_data.js  —  学习资料库（多平台精选）
 * 覆盖平台：B站 / 抖音 / 小红书 / 微信 / 网页(工具·书籍)
 * 字段说明：
 *   name 名称 | type 类型 | desc 简介 | plat 平台
 *   kw   搜索词(用于生成对应平台搜索链接) | tag 标签
 *   url  直链(网页/工具/书籍用；平台类用 kw 自动生成搜索链接)
 * ============================================================ */
window.LEARNING_DATA = [
  {
    id: "wechat",
    name: "微信公众号编辑",
    icon: "📝",
    color: "#ff6b9d",
    desc: "排版、AI 编辑器、涨粉与运营",
    items: [
      { name: "微信公众平台(官方)", type: "平台", plat: "微信", kw: "公众号排版",
        desc: "官方后台，图文编辑、数据分析、自动回复都在这里。" },
      { name: "小墨鹰编辑器（新手推荐）", type: "工具", plat: "网页", tag: "排版",
        desc: "零基础上手、模板丰富，适合公众号图文快速排版。",
        url: "https://news.qq.com/rain/a/20260324A068TO00" },
      { name: "6 款 AI 编辑器实测（保姆级）", type: "评测", plat: "微信", kw: "公众号AI编辑器",
        desc: "亲测 6 款主流公众号 AI 编辑器，3 分钟排出版式高级感。" },
      { name: "2026 公众号编辑器全攻略", type: "教程", plat: "网页", tag: "运营",
        desc: "从选型到专业级排版的完整路径，新媒体运营必看。",
        url: "https://zhuanlan.zhihu.com/p/2048798170554036316" },
      { name: "有一云 AI 排版", type: "工具", plat: "网页", tag: "AI排版",
        desc: "全能型 AI 排版，把排版从反复返工变成直接出效果。",
        url: "https://www.163.com/dy/article/KIP86E5G0556F3FG.html" },
      { name: "秀米 XIUMI", type: "工具", plat: "网页", tag: "排版",
        desc: "经典图文排版工具，样式自由、可存为模板长期复用。",
        url: "https://xiumi.us" },
      { name: "135 编辑器", type: "工具", plat: "网页", tag: "排版",
        desc: "海量样式中心 + 一键排版，适合日更运营。",
        url: "https://www.135editor.com" },
      { name: "B站：公众号排版教程合集", type: "视频", plat: "B站", kw: "公众号排版教程",
        desc: "UP 主实操演示从 0 到高级排版的完整流程。" },
      { name: "小红书：排版爆款笔记参考", type: "图文", plat: "小红书", kw: "公众号排版",
        desc: "看热门公众号的排版样式，抄作业最快。" },
      { name: "抖音：公众号运营博主", type: "视频", plat: "抖音", kw: "公众号运营",
        desc: "短平快讲涨粉、标题、封面技巧。" }
    ]
  },
  {
    id: "communication",
    name: "传播学",
    icon: "📡",
    color: "#9775fa",
    desc: "经典教材、入门书单与理论框架",
    items: [
      { name: "《传播学教程》郭庆光", type: "教材", plat: "网页", tag: "入门必读",
        desc: "最经典的基础读本，人人必备，建议反复读 2-3 遍打底。",
        url: "https://book.douban.com/subject/6598640/" },
      { name: "B站：传播学公开课/名校网课", type: "视频", plat: "B站", kw: "传播学 公开课",
        desc: "中传/复旦等名校传播学课程，系统建立理论框架。" },
      { name: "微信：新榜 / 全媒派 公众号", type: "公众号", plat: "微信", kw: "传播学",
        desc: "行业前沿案例与深度解读，紧跟平台趋势。" },
      { name: "小红书：传播学考点笔记", type: "图文", plat: "小红书", kw: "传播学笔记",
        desc: "把《传播学教程》拆成好记的图文卡片。" },
      { name: "抖音：传播学知识博主", type: "视频", plat: "抖音", kw: "传播学",
        desc: "用 1 分钟讲清一个理论（沉默的螺旋/议程设置等）。" },
      { name: "传播学怎么入门（胡翼青书单）", type: "书单", plat: "网页", tag: "路径",
        desc: "南大胡翼青老师开具的 120 本跨学科书单，建立知识地图。",
        url: "https://www.zhihu.com/question/20356106" },
      { name: "传播学入门书单（易读版）", type: "书单", plat: "网页", tag: "兴趣",
        desc: "尽量非教材、以易读为标准，先引发兴趣再啃理论。",
        url: "https://www.douban.com/doulist/43648988/" },
      { name: "《网络传播概论》彭兰", type: "教材", plat: "网页", tag: "新媒体",
        desc: "理解短视频/社交媒体传播逻辑的必读，贴近抖音实战。",
        url: "https://book.douban.com/subject/26998171/" },
      { name: "《理解媒介》麦克卢汉", type: "经典", plat: "网页", tag: "理论",
        desc: "『媒介即讯息』，建立对平台与技术的底层认知。",
        url: "https://book.douban.com/subject/1095351/" },
      { name: "《娱乐至死》波兹曼", type: "经典", plat: "网页", tag: "理论",
        desc: "反思娱乐化传播，对内容创作者极有启发性。",
        url: "https://book.douban.com/subject/20450811/" },
      { name: "《乌合之众》勒庞", type: "经典", plat: "网页", tag: "群体心理",
        desc: "理解群体情绪与从众心理，写好『群像』内容的基础。",
        url: "https://book.douban.com/subject/1012611/" }
    ]
  },
  {
    id: "lens",
    name: "镜头语言",
    icon: "🎬",
    color: "#4dabf7",
    desc: "运镜、景别、转场与情绪表达",
    items: [
      { name: "B站：影视飓风 · 运镜/分镜", type: "视频", plat: "B站", kw: "影视飓风 运镜",
        desc: "顶级制作团队讲机位、运镜与分镜，质量天花板。" },
      { name: "B站：拉片实验室", type: "视频", plat: "B站", kw: "拉片 镜头语言",
        desc: "逐帧拆解电影镜头语言，直接迁移到短视频。" },
      { name: "小红书：运镜/分镜脚本笔记", type: "图文", plat: "小红书", kw: "运镜教程",
        desc: "手机也能拍的运镜清单 + 分镜模板。" },
      { name: "抖音：运镜教学号", type: "视频", plat: "抖音", kw: "运镜教学",
        desc: "短平快教推拉摇移跟，适合跟练。" },
      { name: "《镜头语言》系统解读（微信读书）", type: "教材", plat: "网页", tag: "系统",
        desc: "移/跟/环绕/甩/升/降镜头、空镜头、主客观镜头、转场全覆盖。",
        url: "https://weread.qq.com/web/bookDetail/0bd32350813abbc29g014680" },
      { name: "景别五段：远全中近特", type: "方法", plat: "网页", tag: "基础",
        desc: "远景定场、全景交代关系、中景叙事、近景情绪、特写戳心——群像片靠中近景切换。" },
      { name: "『一个眼神讲完一个故事』", type: "练习", plat: "抖音", kw: "眼神杀 情绪镜头",
        desc: "结合热梗『悲天悯人眼神杀』，每天练一个特写情绪镜头。" },
      { name: "转场：相似形/动作/视线匹配", type: "方法", plat: "网页", tag: "剪辑",
        desc: "用相似性（形状/颜色/动作）做无缝转场，群像混剪更丝滑。" },
      { name: "固定机位 vs 手持", type: "方法", plat: "网页", tag: "风格",
        desc: "饭桌/谈心用固定机位显克制；漫游用手持显生活感。" }
    ]
  },
  {
    id: "photography",
    name: "摄影",
    icon: "📷",
    color: "#ffa94d",
    desc: "器材、构图、用光与后期",
    items: [
      { name: "B站：摄影师顾俊 / 极地手记", type: "视频", plat: "B站", kw: "摄影师顾俊 摄影教程",
        desc: "职业摄影师讲人像、构图与用光，实操性强。" },
      { name: "小红书：摄影教程笔记", type: "图文", plat: "小红书", kw: "摄影教程 新手",
        desc: "海量新手友好笔记，胶片/日系/氛围感随手抄。" },
      { name: "抖音：手机摄影教学", type: "视频", plat: "抖音", kw: "手机摄影",
        desc: "用一部手机拍出氛围感，适合日常 vlog 取景。" },
      { name: "微信：摄影之友 公众号", type: "公众号", plat: "微信", kw: "摄影之友",
        desc: "器材评测 + 拍摄思路，长期订阅涨审美。" },
      { name: "《兵书十二卷》赵嘉", type: "教材", plat: "网页", tag: "启蒙",
        desc: "入坑启蒙读物，用职业摄影师经历讲透器材与技术核心问题。",
        url: "https://zhuanlan.zhihu.com/p/622201492" },
      { name: "摄影学习书单（技术→理论→后期）", type: "书单", plat: "网页", tag: "路径",
        desc: "分技术与视觉、摄影理论、后期处理三部分的完整书单。",
        url: "https://zhuanlan.zhihu.com/p/62069438" },
      { name: "构图三板斧：三分/引导线/框架", type: "方法", plat: "网页", tag: "构图",
        desc: "三分法稳、引导线带眼走、框架制造窥视感，群像常用框架构图。" },
      { name: "自然光人像", type: "方法", plat: "网页", tag: "用光",
        desc: "窗边柔光 + 逆光发丝光，低成本拍出氛围感（森系穿搭刚需）。" },
      { name: "后期：色调统一大于精修", type: "方法", plat: "网页", tag: "后期",
        desc: "先定系列色调（如奶油/胶片/日系），统一比单张惊艳更重要。" }
    ]
  },
  {
    id: "ielts",
    name: "英语雅思",
    icon: "🌍",
    color: "#38d9a9",
    desc: "听说读写备考、教材与模考",
    items: [
      { name: "B站：雅思王陆 / 杨帅 / Simon", type: "视频", plat: "B站", kw: "雅思王陆 听力语料",
        desc: "听力语料库、口语模板、写作逻辑，分科跟练。" },
      { name: "小红书：雅思经验笔记", type: "图文", plat: "小红书", kw: "雅思经验 自学",
        desc: "大量 7 分/8 分经验帖，找适配自己的方法。" },
      { name: "微信：雅思哥 公众号", type: "公众号", plat: "微信", kw: "雅思哥",
        desc: "当季口语题库 + 范文，每日更新。" },
      { name: "抖音：雅思口语博主", type: "视频", plat: "抖音", kw: "雅思口语",
        desc: "碎片化跟读，练发音和流利度。" },
      { name: "2026 雅思备考计划大全", type: "规划", plat: "网页", tag: "备考",
        desc: "资料汇总 + 各科详细分析 + 评分标准，报考送考官课。",
        url: "https://zhuanlan.zhihu.com/p/2047309715584049446" },
      { name: "IELTS 备考书 155 本评测", type: "评测", plat: "网页", tag: "书单",
        desc: "官方真题/写作/词汇/口语全覆盖，帮你不踩雷。",
        url: "https://www.ielts.international/zh/ielts-preparation-books" },
      { name: "2026 雅思软件排行（含真题/模考）", type: "工具", plat: "网页", tag: "APP",
        desc: "免费软件 TOP5 + 在线模考，利用碎片时间刷真题。",
        url: "https://www.toutiao.com/article/7615442040125407787/" },
      { name: "剑桥雅思真题(Cambridge IELTS)", type: "教材", plat: "网页", tag: "核心",
        desc: "剑 17-19 为主，听力阅读刷真题、写作口语背范文结构。" },
      { name: "口语：Simon 素材 + 雅思哥题库", type: "方法", plat: "网页", tag: "口语",
        desc: "Simon 的 Part2 模板 + 雅思哥当季题库，每日 1 个话题录音自检。" },
      { name: "写作：顾家北 / 王陆语料", type: "方法", plat: "网页", tag: "写作",
        desc: "顾家北逻辑链 + 王陆语料库，积累可复用句型而非背范文。" }
    ]
  },
  {
    id: "vibe",
    name: "vibecoding",
    icon: "🤖",
    color: "#5c7cfa",
    desc: "自然语言编程、AI 辅助开发与工具选型",
    items: [
      { name: "B站：Cursor / Vibe Coding 教程", type: "视频", plat: "B站", kw: "Cursor 教程 Vibe Coding",
        desc: "从装环境到工程化落地的实战演示，跟着做就能跑。" },
      { name: "小红书：AI 编程笔记", type: "图文", plat: "小红书", kw: "vibecoding AI编程",
        desc: "prompt 模板、避坑清单、效率流，短平快。" },
      { name: "抖音：AI 编程博主", type: "视频", plat: "抖音", kw: "AI编程 自然语言编程",
        desc: "看别人怎么用对话『写』出一个应用。" },
      { name: "微信：量子位 / AI 先知 公众号", type: "公众号", plat: "微信", kw: "Vibe Coding",
        desc: "追踪 AI 编程最新工具与方法论。" },
      { name: "Vibe Coding 入门教程（菜鸟教程）", type: "教程", plat: "网页", tag: "入门",
        desc: "用自然语言描述需求即可生成代码，零基础也能上手。",
        url: "https://www.runoob.com/ai-agent/vibe-coding-start.html" },
      { name: "Vibe Coding 完整教程：从入门到进阶", type: "教程", plat: "网页", tag: "工作流",
        desc: "系统讲解从意图描述到工程化落地的完整链路。",
        url: "https://segmentfault.com/a/1190000047772653" },
      { name: "2026 Vibe Coding 实战全指南", type: "实战", plat: "网页", tag: "进阶",
        desc: "编程范式从『写语法』转向『管意图』，提供约束规则的方法。",
        url: "https://blog.csdn.net/2201_75368691/article/details/157943025" },
      { name: "Vibe Coding 2026：从『忘记代码』到工程化", type: "深度", plat: "网页", tag: "认知",
        desc: "92% 美国开发者已日常使用，讲清工程化实践与边界。",
        url: "https://pengjiyuan.github.io/articles/vibe-coding-2026/" },
      { name: "2026 新手 Vibe Coding 工具选型", type: "选型", plat: "网页", tag: "工具",
        desc: "梳理 10 款值得关注的工具（Cursor/Claude/Windsurf/v0/Bolt/Trae 等）。",
        url: "https://www.sohu.com/a/1026718846_122553831" },
      { name: "实战心法：先画原型再写提示词", type: "方法", plat: "网页", tag: "心法",
        desc: "把『我要做一个 XX』拆成界面/数据/交互三块分别描述，AI 产出更可控。" }
    ]
  },
  {
    id: "sql",
    name: "SQL",
    icon: "🗄️",
    color: "#f783ac",
    desc: "查询、分析与你自己的内容数据复盘",
    items: [
      { name: "B站：黑马/尚硅谷 SQL 教程", type: "视频", plat: "B站", kw: "SQL 教程 零基础",
        desc: "体系完整、案例多，适合从 0 打通查询与联表。" },
      { name: "小红书：SQL 面试笔记", type: "图文", plat: "小红书", kw: "SQL 面试题",
        desc: "高频题 + 窗口函数套路，边看边练。" },
      { name: "微信：数据分析类公众号", type: "公众号", plat: "微信", kw: "SQL 数据分析",
        desc: "用真实业务场景讲 SQL，顺便学指标体系。" },
      { name: "抖音：SQL 速通", type: "视频", plat: "抖音", kw: "SQL 入门",
        desc: "几分钟讲清一个语法点，通勤刷着学。" },
      { name: "SQL 教程（菜鸟教程）", type: "教程", plat: "网页", tag: "入门",
        desc: "SELECT/JOIN/聚合/子查询全覆盖，边看边练。",
        url: "https://www.runoob.com/sql/sql-tutorial.html" },
      { name: "SQLZoo 交互练习", type: "练习", plat: "网页", tag: "刷题",
        desc: "浏览器里直接写 SQL 即时反馈，最适合零基础。",
        url: "https://sqlzoo.net" },
      { name: "LeetCode 数据库题库", type: "练习", plat: "网页", tag: "进阶",
        desc: "中等/困难题练窗口函数与复杂 JOIN，面试与实战通吃。",
        url: "https://leetcode.cn/problemset/database/" },
      { name: "《SQL 必知必会》", type: "教材", plat: "网页", tag: "经典",
        desc: "薄而精，几天读完即可应付日常查询与分析。",
        url: "https://book.douban.com/subject/35166068/" },
      { name: "用 SQL 复盘你的抖音数据", type: "实战", plat: "网页", tag: "应用",
        desc: "把发布记录导入表格，用 GROUP BY 看哪种『群像角度』播放最高。" }
    ]
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    color: "#82c91e",
    desc: "自动化、数据分析与爬虫入门",
    items: [
      { name: "B站：码农高天 / 技术蛋老师", type: "视频", plat: "B站", kw: "Python 教程 零基础",
        desc: "风趣易懂的入门路线，跟着敲代码。", },
      { name: "小红书：Python 学习笔记", type: "图文", plat: "小红书", kw: "Python 学习 路线",
        desc: "路线图 + 项目清单，避免学到一半迷路。" },
      { name: "微信：Python 之禅 公众号", type: "公众号", plat: "微信", kw: "Python",
        desc: "进阶技巧与实战项目，长期订阅。" },
      { name: "抖音：Python 自动化", type: "视频", plat: "抖音", kw: "Python 自动化",
        desc: "看用几十行代码搞定重复工作的爽片。" },
      { name: "Python3 教程（菜鸟教程）", type: "教程", plat: "网页", tag: "入门",
        desc: "语法 + 标准库 + 小例子，零基础友好。",
        url: "https://www.runoob.com/python3/python3-tutorial.html" },
      { name: "廖雪峰 Python 教程", type: "教程", plat: "网页", tag: "系统",
        desc: "中文、系统、带实战，适合打牢基础。",
        url: "https://liaoxuefeng.com/python3/" },
      { name: "《Python编程：从入门到实践》", type: "教材", plat: "网页", tag: "项目",
        desc: "前半基础、后半 3 个项目，做完即有作品集。",
        url: "https://book.douban.com/subject/35196268/" },
      { name: "Automate the Boring Stuff", type: "教材", plat: "网页", tag: "自动化",
        desc: "用 Python 自动化重复工作（批量重命名/爬网页/处理表格）。",
        url: "https://automatetheboringstuff.com" },
      { name: "Real Python", type: "教程", plat: "网页", tag: "进阶",
        desc: "大量中高阶实战教程，配代码可下载。",
        url: "https://realpython.com" },
      { name: "用 Python 写你的抖音爬取脚本", type: "实战", plat: "网页", tag: "应用",
        desc: "参考本工作台的 douyin_crawler.py，requests + 正则即可抓热榜。",
        url: "https://www.python.org" }
    ]
  },
  {
    id: "douyin-ops",
    name: "抖音运营(附赠)",
    icon: "🎵",
    color: "#ff8787",
    desc: "算法、发布节奏与涨粉方法论",
    items: [
      { name: "抖音：抖音创作者中心 / 巨量算数", type: "账号", plat: "抖音", kw: "抖音创作者中心",
        desc: "官方数据看板与热点榜单，发前必看。" },
      { name: "微信：新榜 / 抖音创作者 公众号", type: "公众号", plat: "微信", kw: "抖音运营",
        desc: "爆款拆解 + 平台规则变化，第一时间同步。" },
      { name: "小红书：抖音运营笔记", type: "图文", plat: "小红书", kw: "抖音运营 起号",
        desc: "素人起号、投流、脚本模板，实战派很多。" },
      { name: "B站：抖音运营教程", type: "视频", plat: "B站", kw: "抖音运营 涨粉",
        desc: "系统讲算法、选题、发布时间，适合建立方法论。" },
      { name: "2026 抖音爆款全攻略", type: "攻略", plat: "网页", tag: "爆款",
        desc: "算法规则+选题+拍摄剪辑+发布运营+真实案例全维度拆解。",
        url: "https://www.toutiao.com/article/7606440401465000498/" },
      { name: "2026 创作指南：十大灵感选题", type: "选题", plat: "网页", tag: "灵感",
        desc: "新榜从年度精选总结的十大方向，本工作台已对齐你的赛道。",
        url: "https://news.qq.com/rain/a/20251231A03A1V00" },
      { name: "13 位达人涨粉千万的密码", type: "案例", plat: "网页", tag: "涨粉",
        desc: "纯追热点已失效，能涨粉的都在为观众提供『情绪价值/实用价值』。",
        url: "https://news.qq.com/rain/a/20260109A066UV00" },
      { name: "2026 抖音 28 种变现全解", type: "变现", plat: "网页", tag: "搞钱",
        desc: "0 粉也能参与的变现路径，副业起步参考。",
        url: "https://zhuanlan.zhihu.com/p/2061145043948327485" },
      { name: "蝉妈妈热榜（每日参考）", type: "数据", plat: "网页", tag: "榜单",
        desc: "看全行业当日爆款，找可二创的选题方向。",
        url: "https://www.chanmama.com/open/hotAwemeRank.html" }
    ]
  }
];

/* 平台搜索链接生成（供工作台渲染时调用） */
window.platSearch = function(plat, kw){
  const q = encodeURIComponent(kw||"");
  switch(plat){
    case "B站":   return "https://search.bilibili.com/all?keyword="+q;
    case "抖音":   return "https://www.douyin.com/search/"+q;
    case "小红书": return "https://www.xiaohongshu.com/search_result?keyword="+q;
    case "微信":   return "https://weixin.sogou.com/weixin?query="+q;
    default:       return "";
  }
};
window.PLAT_LIST = ["B站","抖音","小红书","微信","网页"];
